# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-21 07:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('computer science', 'CS'), ('information technology', 'IT'), ('mechanical', 'ME'), ('electronics', 'EC'), ('electrical', 'EE'), ('electrical and electronics', 'EEE'), ('civil', 'CE'), ('instrumentation ansd control', 'IC')], max_length=20)),
                ('semester', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth'), ('fifth', 'Fifth'), ('sixth', 'Sixth'), ('seventh', 'Seventh'), ('eighth', 'Eighth')], max_length=20)),
                ('section', models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3')], max_length=5)),
                ('subject', models.CharField(max_length=20)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phoneno', models.CharField(max_length=15)),
                ('createdAt', models.DateField(default=datetime.date.today)),
                ('sclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attend.Class')),
            ],
        ),
    ]
