# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-02 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0002_auto_20160803_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('ME', 'Mechanical Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EE', 'Electrical Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('CE', 'Civil Engineering'), ('ICE', 'Instrumentation and Control Engineering')], max_length=20),
        ),
    ]
