# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-03 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0003_auto_20160803_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='add_no',
            field=models.CharField(default='Admission No', max_length=10),
        ),
    ]
