# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-04 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0005_student_univ_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='add_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='univ_roll_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
