# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-08 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0006_auto_20160804_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
