# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-08 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0008_class_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='total',
        ),
    ]
