# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-16 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0010_student_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
                ('sender', models.EmailField(max_length=50)),
            ],
        ),
    ]
